@baseUrl = http://localhost:3000

### Read all films 
GET {{baseUrl}}/films


### Create a film
POST {{baseUrl}}/films/
Content-Type: application/json

{
  "title": "GI-JOE 2: Le retour",
  "duration": 123,
  "budget": 201,
  "link":"www.moodle.vinci.be"
}

### Delete the film with ID == 2
DELETE {{baseUrl}}/films/2

### Patch the films with ID == 2
PATCH {{baseUrl}}/films/3
Content-Type: application/json

{
  "title":"Star Wars: Episode II – Attack of the Clones",
  "budget": 1111
}